import {
  IconDashboard,
  IconBranches,
  IconRoles,
  IconUsers,
  IconLearners,
  IconGuardian,
  IconAuditLog,
  IconSettings,
} from '@shared/components/icons';
import { PERMISSIONS, ROLES } from '@core/permissions';
import type { NavSectionConfig } from './navigation.types';

export const navigationConfig: NavSectionConfig[] = [
  {
    id: 'main-menu',
    title: 'Main Menu',
    titleKey: 'nav.mainMenu',
    items: [
      {
        id: 'dashboard',
        to: '/dashboard',
        label: 'Dashboard',
        labelKey: 'nav.dashboard',
        icon: IconDashboard,
        roles: [ROLES.ADMIN, ROLES.INSTRUCTOR, ROLES.STUDENT],
        permissions: [PERMISSIONS.DASHBOARD_VIEW],
      },
      {
        id: 'branches',
        to: '/branches',
        label: 'Branches',
        labelKey: 'nav.branches',
        icon: IconBranches,
        roles: [ROLES.ADMIN],
        permissions: [PERMISSIONS.BRANCH_MANAGE],
      },
      {
        id: 'roles',
        to: '/roles',
        label: 'Roles & Permissions',
        labelKey: 'nav.roles',
        icon: IconRoles,
        roles: [ROLES.ADMIN],
        permissions: [PERMISSIONS.ROLE_MANAGE],
      },
      {
        id: 'users',
        to: '/users',
        label: 'Users',
        labelKey: 'nav.users',
        icon: IconUsers,
        roles: [ROLES.ADMIN],
        permissions: [PERMISSIONS.USER_MANAGE],
      },
      {
        id: 'learners',
        to: '/learners',
        label: 'Learners',
        labelKey: 'nav.learners',
        icon: IconLearners,
        roles: [ROLES.ADMIN, ROLES.INSTRUCTOR],
        permissions: [PERMISSIONS.LEARNER_MANAGE],
      },
      {
        id: 'guardian',
        to: '/guardian',
        label: 'Guardian',
        labelKey: 'nav.guardian',
        icon: IconGuardian,
        roles: [ROLES.ADMIN],
        permissions: [PERMISSIONS.GUARDIAN_MANAGE],
      },
      {
        id: 'audit-log',
        to: '/audit-log',
        label: 'Audit Log',
        labelKey: 'nav.auditLog',
        icon: IconAuditLog,
        roles: [ROLES.ADMIN],
        permissions: [PERMISSIONS.AUDIT_VIEW],
      },
      {
        id: 'settings',
        to: '/settings',
        label: 'Settings',
        labelKey: 'nav.settings',
        icon: IconSettings,
        roles: [ROLES.ADMIN],
        permissions: [PERMISSIONS.SETTINGS_MANAGE],
      },
    ],
  },
];
