export const ROLES = {
  ADMIN: 'ADMIN',
  INSTRUCTOR: 'INSTRUCTOR',
  STUDENT: 'STUDENT',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const PERMISSIONS = {
  // Dashboard Permissions
  DASHBOARD_VIEW: 'dashboard:view',

  // Core Management Permissions
  BRANCH_MANAGE: 'branch:manage',
  ROLE_MANAGE: 'role:manage',
  USER_MANAGE: 'user:manage',
  LEARNER_MANAGE: 'learner:manage',
  GUARDIAN_MANAGE: 'guardian:manage',
  AUDIT_VIEW: 'audit:view',
  SETTINGS_MANAGE: 'settings:manage',

  // Course Permissions
  COURSE_READ: 'course:read',
  COURSE_CREATE: 'course:create',
  COURSE_UPDATE: 'course:update',
  COURSE_DELETE: 'course:delete',

  // Assignment Permissions
  ASSIGNMENT_READ: 'assignment:read',
  ASSIGNMENT_CREATE: 'assignment:create',
  ASSIGNMENT_SUBMIT: 'assignment:submit',
  ASSIGNMENT_GRADE: 'assignment:grade',

  // Quiz Permissions
  QUIZ_READ: 'quiz:read',
  QUIZ_TAKE: 'quiz:take',
  QUIZ_MANAGE: 'quiz:manage',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.BRANCH_MANAGE,
    PERMISSIONS.ROLE_MANAGE,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.LEARNER_MANAGE,
    PERMISSIONS.GUARDIAN_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.COURSE_READ,
    PERMISSIONS.COURSE_CREATE,
    PERMISSIONS.COURSE_UPDATE,
    PERMISSIONS.COURSE_DELETE,
    PERMISSIONS.ASSIGNMENT_READ,
    PERMISSIONS.ASSIGNMENT_CREATE,
    PERMISSIONS.ASSIGNMENT_SUBMIT,
    PERMISSIONS.ASSIGNMENT_GRADE,
    PERMISSIONS.QUIZ_READ,
    PERMISSIONS.QUIZ_TAKE,
    PERMISSIONS.QUIZ_MANAGE,
  ],
  INSTRUCTOR: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.LEARNER_MANAGE,
    PERMISSIONS.COURSE_READ,
    PERMISSIONS.COURSE_CREATE,
    PERMISSIONS.COURSE_UPDATE,
    PERMISSIONS.ASSIGNMENT_READ,
    PERMISSIONS.ASSIGNMENT_CREATE,
    PERMISSIONS.ASSIGNMENT_GRADE,
    PERMISSIONS.QUIZ_READ,
    PERMISSIONS.QUIZ_MANAGE,
  ],
  STUDENT: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COURSE_READ,
    PERMISSIONS.ASSIGNMENT_READ,
    PERMISSIONS.ASSIGNMENT_SUBMIT,
    PERMISSIONS.QUIZ_READ,
    PERMISSIONS.QUIZ_TAKE,
  ],
};
